name: Build CarLauncher.apk
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout OsmAnd
      uses: actions/checkout@v6
      with:
        path: android
    - name: checkout OsmAnd-resources
      uses: actions/checkout@v6
      with:
        repository: osmandapp/OsmAnd-resources
        path: resources
    - name: checkout OsmAnd-core
      uses: actions/checkout@v6
      with:
        repository: osmandapp/OsmAnd-core
        path: core
    - name: checkout OsmAnd-core-legacy
      uses: actions/checkout@v6
      with:
        repository: osmandapp/OsmAnd-core-legacy
        path: core-legacy
    - name: checkout OsmAnd-build
      uses: actions/checkout@v6
      with:
        repository: osmandapp/OsmAnd-build
        path: build
    - name: checkout OsmAnd-tools
      uses: actions/checkout@v6
      with:
        repository: osmandapp/OsmAnd-tools
        path: tools
    - name: checkout OsmAnd-misc
      uses: actions/checkout@v6
      with:
        repository: osmandapp/OsmAnd-misc
        path: misc

    - name: Setup Android SDK and NDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'ndk;25.1.8937393'

    - name: set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      working-directory: ./android
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: ./android
      run: ./gradlew assemblecarlauncherLegacyFatDebug -x test --no-daemon

    - name: Prepare Release Info
      working-directory: ./android
      run: |
        VERSION_CODE=$(git rev-list --count HEAD)
        VERSION_NAME="1.0.${VERSION_CODE}"
        echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
        echo "{\"versionCode\": ${VERSION_CODE}, \"versionName\": \"${VERSION_NAME}\", \"apkUrl\": \"https://github.com/${{ github.repository }}/releases/latest/download/CarLauncher.apk\"}" > version.json

    - name: Rename APK
      working-directory: ./android
      run: cp OsmAnd/build/outputs/apk/carlauncherLegacyFat/debug/OsmAnd-carlauncher-legacy-fat-debug.apk CarLauncher.apk

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION_NAME }}
        name: Release ${{ env.VERSION_NAME }}
        files: |
          android/CarLauncher.apk
          android/version.json
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
